### ISSUE TITLE
Compile errors in Arduino IDE

### ISSUE THREAD

**Issue by novolec** [jsmith628/max22200_Arduino#1]
Hello,
When I add this library to my Arduino IDE (version 2.3.2) and include it in a sketch, it gives compilation errors as copied below. If I comment out the offending functions then it compiles fine.

>>>
C:\Users\bradl\OneDrive\Documents\Arduino\libraries\MAX22200\MAX22200.cpp: In member function 'MAX22200::ChannelMode MAX22200::getChannelMode(uint8_t)':
C:\Users\bradl\OneDrive\Documents\Arduino\libraries\MAX22200\MAX22200.cpp:246:18: error: invalid conversion from 'uint32_t' {aka 'unsigned int'} to 'MAX22200::ChannelMode' [-fpermissive]
     return (0b11 & (status >> (MAX22200_CM10 + ch)));
            ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\bradl\OneDrive\Documents\Arduino\libraries\MAX22200\MAX22200.cpp: In member function 'MAX22200::ChannelConfig MAX22200::readChannelConfig(uint8_t)':
C:\Users\bradl\OneDrive\Documents\Arduino\libraries\MAX22200\MAX22200.cpp:278:20: error: could not convert '((MAX22200*)this)->MAX22200::read32(((int)((uint8_t)(1 + ((int)ch)))))' from 'uint32_t' {aka 'unsigned int'} to 'MAX22200::ChannelConfig'
     return ( read32(MAX22200_CFG_CH1+ch) );
            ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~

exit status 1

Compilation error: exit status 1

<<<

**Comment by jsmith628** [comment]
Thanks for the report.

Seems to be a type error that slipped past me. Should be fixed now.

Let me know if it works, then I'll close the issue.

**Comment by novolec** [comment]
thanks - looks to be working ok now
